:seedling: [WIP] Runtimesdk/validate handlers on discovery
sbueringer/cluster-api pull request #28
Opened 2022-04-16 13:21 UTC by killianmuldoon

Signed-off-by: killianmuldoon <kmuldoon@vmware.com>

Add first round of validation rules on discovery of extensions in the extension controller.

2022-04-20 02:41 UTC, ykakarap requested changes

2022-04-20 02:41 UTC, ykakarap commented on exp/runtime/internal/controllers/extension_controller.go
>  	for _, runtimeExtension := range ext.Status.RuntimeExtensions {
How about also adding a validation rule to make sure that the hook is valid?

2022-04-20 02:41 UTC, ykakarap commented on exp/runtime/internal/controllers/extension_controller.go
> +		if *runtimeExtension.TimeoutSeconds < 0 && *runtimeExtension.TimeoutSeconds > 600 {
10 minutes for maximum timeout seems too long. The admission webhooks in k8s allow a maximum timeout of 30s. 
How about using the same for our maximum as well?

2022-04-20 02:41 UTC, ykakarap commented on exp/runtime/internal/controllers/extension_controller.go
> +			runtimeExtension.TimeoutSeconds = pointer.Int32(0)
A 0s timeout means if the user does not set a timeout the network call will always timeout. The admission webhooks in k8s default to a timeout of 10s. We should also probably use the same timeout as default.

2022-06-01 09:59 UTC, killianmuldoon commented
Closing in favor of #https://github.com/kubernetes-sigs/cluster-api/pull/6578

2022-06-01 09:59 UTC, closed without merging